version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:12.6-alpine
    restart: always
    env_file:
      - postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.30
    restart: always
    env_file:
      - pgadmin.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - postgres
    depends_on:
      - postgres

  redis:
    container_name: 'redis'
    image: 'redis:6.0.10-alpine'
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'

  zookeeper:
    container_name: 'zookeeper'
    image: wurstmeister/zookeeper
    expose:
      - "2181"

  kafka:
    container_name: 'kafka'
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - kafka/:/etc/kafka
  
  vertica:
    container_name: 'vertica'
    image: dataplatform/docker-vertica
    ports:
      - "5433:5433"  
    volumes:
      - /vertica_data:/home/dbadmin/docker

volumes:
  postgres:
  pgadmin:
  redis:
  zookeeper:
  kafka:
  vertica:
