version: '3.8'
services:
  keycloak:
    container_name: keycloak-dev
    image: quay.io/keycloak/keycloak:21.1.1
    command: ["start-dev", "--import-realm", "--http-port=8180"]
    ports:
      - "8180:8180"
      - "8843:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/data/certs/keycloak.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/data/certs/keycloak.key

    volumes:
      - ./data/realm.json:/opt/keycloak/data/import/realm.json:ro
      - ./certs:/opt/keycloak/data/certs
    networks:
      - keycloak-dev-network

networks:
  keycloak-dev-network:
    driver: bridge