version: '3.8'
services:
  keycloak:
    container_name: keycloak-dev
    image: quay.io/keycloak/keycloak:21.1.1
    command: ["start-dev", "--import-realm", "--http-port=8180"]
    ports:
      - "8180:8180"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./data/realm.json:/opt/keycloak/data/import/realm.json:ro